name: aks-fpga
on:
  push:
    branches:
    - main
    - dev
  workflow_dispatch: {}

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  REPO: docker.io/alexeldeib
  IMG_PREFIX: aks-fpga

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v1.0.0'
    - name: Configure token
      run: |
        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value | tee token
    - name: build image
      run: |
        set -euo pipefail
        docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
        TAG=$(date -Ihours | tr :+ -)
        echo "TAG: ${TAG}"
        docker build -t ${REPO}/${IMG_PREFIX}:${TAG} .
        docker tag ${REPO}/${IMG_PREFIX}:${TAG} ${REPO}/${IMG_PREFIX}:latest
        docker push ${REPO}/${IMG_PREFIX}:${TAG}
        docker push ${REPO}/${IMG_PREFIX}:latest
    - name: Sign artifact
      run: |
        cosign sign --identity-token="$(cat token)" ${REPO}/${IMG_PREFIX}:latest
