name: Example
on:
  push:
    branches:
    - dev
  workflow_dispatch: {}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.0.0'
      - name: Configure token
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value | tee token
      - name: Sign artifact
        run: |
          cosign sign --identity-token="$(cat token)"
      # - uses: actions/upload-artifact@v1
      #   with:
      #     name: token
      #     path: token

